### PR TITLE
Scroll Playback

### PR DESCRIPTION
**Pull request by mixcas**
I took a diff approach with manual control and using 2 different videos and switching them depending on the position.

This doesn't not solve the mobile issue with autoplay.

@varffs no, the scroll position is not tightly bound to the video position (skip). It just plays a video or another depending on the position.

Sidenote:
For the mobile i want to try skipping thru the video on a timeout basis. Another alternative is using [canvid](https://github.com/gka/canvid)

### CODE REVIEW

**Comment by varffs** [comment]
I haven't reviewed the code just tested it. There seems to be one strange bug, but I don't really understand the intention again. I think we should have a general call about this. I don't understand why we aren't building this according to what Mikey told me last week, but maybe just crossed wires.

**Comment by varffs** [comment]
(sorry the bug was something strange where on my scroll back up I got show the first frame of one of the videos for a split second and then it set to the correct position. I couldnt work out how to replicate it but might be a loading issue)

**Comment by mikeyrayvon** [comment]
i think i told you some wrong shit and then cas explained it to me and i forgot to pass it on.  i thought it was like scrubbing but it's just cue points in the scroll that play bits of the vid. which is what makes it smooth like on the mac pro site. maybe you're referring to something else tho?

**Comment by mixcas** [comment]
I will rewrite using [Waypoints](http://imakewebthings.com/waypoints/api/waypoint/) since it seems like we would use it for the rest of the project.

**Comment by mixcas** [comment]
Ready @varffs

**Pull request merged**
